project:
  type: website
  execute-dir: file
  output-dir: _site
  preview: 
    port: 3000
    host: 127.0.0.1
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Luis Francisco Gómez López (aka luifrancgom)"
  description: "Economist interested in Data Science | Learning: Statistical Learning, R-πthon, Microeconomics and Macroeconomics"
  site-url: https://luifrancgom.github.io/
  repo-url: https://github.com/luifrancgom/luifrancgom.github.io
  favicon: images/fox_gold.png
  search:
    location: navbar
    type: textbox
    limit: 20
  navbar:
    title: "Luis Francisco Gómez López"
    logo: images/fox_gold.png
    logo-alt: "A circle logo featuring a gold fox design"
    background: "#f8f9fa"
    foreground: "#545555"
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: docs/cv/index.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
      - text: "Teaching"
        href: docs/teaching/index.qmd
      - text: "Projects"
        href: docs/projects/index.qmd
      - text: "Tales"
        href: docs/tales/index.qmd
      - text: "Personal"
        href: docs/personal/index.qmd
    right: 
      - icon: twitter
        href: https://twitter.com/luifrancgom/
        aria-label: "Link to luifrancgom Twitter"
        target: _blank
        rel: noopener noreferrer
      - icon: youtube
        href: https://www.youtube.com/@luifrancgom
        aria-label: "Link to luifrancgom Youtube"
        target: _blank
        rel: noopener noreferrer
      - icon: linkedin
        href: https://www.linkedin.com/in/luifrancgom
        aria-label: "Link to luifrancgom LinkedIn"
        target: _blank
        rel: noopener noreferrer
      - icon: github
        href: https://github.com/luifrancgom
        aria-label: "Link to luifrancgom Github"
        target: _blank
        rel: noopener noreferrer
      - icon: stack-overflow
        href: https://stackoverflow.com/users/11192275/luifrancgom
        aria-label: "Link to luifrancgom Stack Overflow"
        target: _blank
        rel: noopener noreferrer
      - icon: envelope-at
        href: mailto:luifrancgom@gmail.com
        aria-label: "Send email to luifrancgom"
    pinned: false
    collapse: true
    collapse-below: lg
  page-navigation: true
  page-footer:
    background: "#f8f9fa"
    foreground: "#545555"
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var copyright.year >}} Luis Francisco Gómez López</span>
      <span class="faux-block">Licensed under {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">Creative Commons CC BY 4.0</a></span>
      <span class="faux-block"> {{< fa brands github >}} <a href="https://github.com/luifrancgom/luifrancgom.github.io" target="_blank" rel="noopener noreferrer">Source code</a></span>
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> <a href="https://orcid.org/0000-0002-2877-9015" target="_blank" rel="noopener noreferrer">0000-0002-2877-9015</a></span>
    right: |
      <span class="faux-block"> Designed with {{< fa heart >}} and {{< fa brain >}} </span>
      <span class="faux-block">Build with {{< fa brands r-project >}} and <a href="https://quarto.org/" target="_blank" rel="noopener noreferrer">Quarto</a></span>

execute: 
  freeze: auto
    
format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true
    bibliography: bibliography/luifrancgom.github.io.bib
    csl: bibliography/apa_7_edition.csl

editor: visual